trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ciartifacts
    source: Manideep1197.modern_dw_DevOps
    trigger: 
      branches:
      - master
  repositories:
  - repository: modern_dw_DevOps
    type: github
    endpoint: DW_GitHub
    name: Manideep1197/modern_dw_DevOps
    ref: adf_publish

# The deployment script sets this as a Pipeline Variable, but you may choose to set it here in the definition
#
variables:
  devAdfName: mdwdoadfdev3la2n

stages:
- stage: deploy_to_dev
  displayName: 'Deploy to DEV'  # In DEV, excludes publishing to ADF as this is a manual publish step
  variables:
  - group: mdwdo-park-release-dev
  - group: mdwdo-park-release-secrets-dev
  jobs:
  - template: templates/jobs/deploy-databricks-job.yml
    parameters:
      environmentName: 'DEV'
  - template: templates/jobs/deploy-azuresqldb-job.yml
    parameters:
      environmentName: 'DEV'
      serviceConnection: 'mdwdo-park-serviceconnection-dev'
